### ISSUE TITLE
link within FAQ fails (not finding its source here)

### ISSUE THREAD

**Issue by carehart** [ortus-boxlang/boxlang-docs#29]
Folks, the FAQ at the bottom of the front page of the site (https://www.boxlang.io/#faq) has a failing link in one of the answers. But I couldn't find the site source in Github, or even that FAQ content. Does it exist? Sorry if I am mistaken, otherwise I would have offered a PR instead of an issue.

The issue is in the answer to the FAQ question, "Can BoxLang® run ColdFusion/CFML code?", where after its two paragraphs it then offers a link for "Read about ColdFusion/CFML", which tries to link to https://boxlang.ortusbooks.com/getting-started/overview/language-differences/coldfusion-cfml, but it currently fails with "page not found".

And though I found that section in this repo, as /getting-started/overview/, it doesn't show a page whose name seems close to that coldfusion-cfml. Perhaps the content was folded into another page, and this link has just not been corrected.

**Comment by lmajano** [comment]
Ok, on it.

**Comment by lmajano** [comment]
They are correcting today
