### ISSUE TITLE
Any discussion of "Multi-Site Management" feature?

### ISSUE THREAD

**Issue by carehart** [ortus-boxlang/boxlang-docs#31]
Folks, in the page about plans (https://www.boxlang.io/plans) one of the distinctions of the + edition is "Multi-Site Management and deployment". 

I've not yet been able to find anything to explain that. I've seen the phrase used in discussions relative to ContentBox (and a casts talk by Jon), but as for BoxLang is there anything that might help us appreciate how the concept(s) would apply here?

**Comment by lmajano** [comment]
This is about CommandBox Multi-Site.  It's part of the CommandBox PRO license, so this translates into BoxLang.

**Comment by carehart** [comment]
Thanks. (And now I do find some resources on that. Can't fathom why it didn't come up on my searching earlier, but that's on me.) 

That said, for folks coming to boxlang without prior Commandbox experience (or more specifically its Pro edition or that multi-site capability), it would seem helpful to offer a bit of clarification somewhere in the boxlang site or docs.

I appreciate that it can feel redundant, but consider that some folks are coming to the site without prior Commandbox experience, or not much. They may be considering the prospect of using boxlang as a means to deploy cfml as an alternative to running either CF or Lucee (which they're hearing about more and more). And they may see the pricing page and wonder about the various benefits of bx+. 

Until that might be offered and in case such folks may find this discussion, here are a couple of key introductory links on multi site in Commandbox:

https://commandbox.ortusbooks.com/embedded-server/multi-site-support

https://commandbox.ortusbooks.com/embedded-server/multi-site-support/multi-site-examples

As always, just trying to help.

**Comment by lmajano** [comment]
Totally. I have disseminated the information internally.
