### ISSUE TITLE
failure in attempting to use bx-compat-cfml in miniserver container image

### ISSUE THREAD

**Issue by carehart** [ortus-boxlang/boxlang-docs#33]
In trying to using the `miniserver` container image and have it implement the `bx-compat-cfml` module (with the image's `BOXLANG_MODULES` env var), I find that it fails with an error, "`End-of-central-directory signature not found`". 

The error details are below (from running the container via compose, using the [compose example offered in the docs](https://boxlang.ortusbooks.com/getting-started/running-boxlang/docker#docker-compose-for-bx-web-server-12). BTW, I've filed a PR to correct the error there of a `docker pull` in the `image` element.)

Note also that the version being pulled down is the 1.0 version, rather than the latest stable 1.15 as available [per forgebox](https://forgebox.io/view/bx-compat-cfml#versions). I tried specifying a different version, in case that may help, but the docs don't clarify how to do it. Attempting `BOXLANG_MODULES=bx-compat-cfml@1.16.0-snapshot` did not work.

FWIW, I also tried specifying a different tag for the image also: `miniserver-snapshot` instead of just `miniserver`, but got the same error.

Below is the detail of the error I got:

```
bxweb-1  | *************************************************************************
bxweb-1  | Welcome to the BoxLang® Module Quick Installer
bxweb-1  | *************************************************************************
bxweb-1  | This will download and install the requested module into you
bxweb-1  | BoxLang® HOME directory at [/root/.boxlang/modules/bx-compat-cfml]
bxweb-1  | *************************************************************************
bxweb-1  | You can also download the BoxLang® modules from https://forgebox.io
bxweb-1  | *************************************************************************
bxweb-1  | Downloading Module [bx-compat-cfml] from [https://downloads.ortussolutions.com/ortussolutions/boxlang-modules/bx-compat-cfml/1.0.0/bx-compat-cfml-1.0.0.zip]
bxweb-1  | Please wait...
bxweb-1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
bxweb-1  |                                  Dload  Upload   Total   Spent    Left  Speed
100  1349    0  1349    0     0   4882      0 --:--:-- --:--:-- --:--:--  4870
bxweb-1  |
bxweb-1  | Module downloaded, continuing installation...
bxweb-1  |
bxweb-1  |
bxweb-1  | Unzipping Module...
bxweb-1  |
bxweb-1  | Archive:  /tmp/bx-compat-cfml.zip
bxweb-1  |   End-of-central-directory signature not found.  Either this file is not
bxweb-1  |   a zipfile, or it constitutes one disk of a multi-part archive.  In the
bxweb-1  |   latter case the central directory and zipfile comment will be found on
bxweb-1  |   the last disk(s) of this archive.
bxweb-1  | unzip:  cannot find zipfile directory in one of /tmp/bx-compat-cfml.zip or
bxweb-1  |         /tmp/bx-compat-cfml.zip.zip, and cannot find /tmp/bx-compat-cfml.zip.ZIP, period.
```

**Comment by bdw429s** [comment]
Hi @carehart , this is the repo for the docs and not really a support forum.  If you're having issues, can you report these in our Community forum, on Slack, or in JIRA?

**Comment by carehart** [comment]
Well. I filed it here as a comment related to that pr (in that even with that correction, it still failed to start if using that module as documented). I thought perhaps whoever dealt with the one issue might have a ready answer on the other--and that perhaps it was simply another doc issue where it (and I) could be corrected. :-) 

But I understand, and will do.

**Comment by carehart** [comment]
BTW, Brad, I just noticed you didn't list opening an issue in github (in the bx-image repo) as an option. Was that just an oversight, or is one those other 3 really preferred over github issues for some reason? Asking not only for me but for others who may come across a thread like this and wonder about this.

I appreciate that it's challenging that people might use four different possible means to report issues. That's life in IT these days, of course. Since some MAY favor github issues, I just want to clarify if they're not preferred by you all for some reason, or for some matters.

**Comment by bdw429s** [comment]
We don't tend to use GitHub issues for most of our projects with few exceptions.  We try to keep everything in JIRA as things in GitHub just get lost so easily amongst all the repos.  When creating an issue in JIRA, we have options in the "Components" drop down for each module (and if we're missing a module we'll add it).  That's where we prefer to keep stuff so we can track better.  In fact, I turn off GitHub issues in most of the repos I control just to help prevent the confusion of people wanting to post there.

**Comment by carehart** [comment]
There you go. Thanks for the clarification :-)
