### ISSUE TITLE
Release notes links missing

### ISSUE THREAD

**Issue by bendur** [ortus-boxlang/boxlang-docs#8]
I think links to release notes were supposed to be here:

https://github.com/ortus-boxlang/boxlang-docs/blob/bf90ddbf671de9fd5cd810d4037d2a07b0faa64f/readme/release-history/README.md?plain=1#L30-L34

**Comment by bdw429s** [comment]
@lmajano Is this resolved?

**Comment by lmajano** [comment]
Done
